name: issue demo
on:
  issues:
    branches: ["main"] 
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check only
        run: echo "hellow"
    
      
    
