name: marix demo

on: 
  push:
    branches: ["main"]
jobs:
  test:
    name: testing
    strategy: 
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: python
        run : echo hi

        

      

