name: marix demo

on: 
  push:
    branches: ["main"]
jobs:
  test:
    name: testing
    strategy: 
      matrix:
        os:  [ubuntu-22.04, ubuntu-20.04,ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: check python version
        run : python --version

        

      

