name: self matrix test
on: 
  push:
    branches: ["main"]
jobs:
  build:
    name: building
    strategy: 
      matrix: 
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            python: ok  

    runs-on: ${{matrix.os}}
    steps:
      - name: show files
        run: ls
      - if: ${{matrix.python}}
        name: check python verison
        run:  python --version
      